# Teaching Assistants

The teaching assistants for 431 this year are Bob Winkelman, Satyakam Mishra, Maher Kazimi and Terry Cui. They are the people answering 431-help at case dot edu, and they are the people holding the bulk of our office hours. Most of them has been in your shoes - they've taken the course in the past, and they enjoyed it enough to come back for more. Many have volunteered their precious time and energy to help make the course happen, and we couldn't be more delighted to welcome you to the course.

To contact the TAs, email `431-help at case dot edu`, which is open all semester.

## Office Hours for TAs

Office hours will be announced in the first week of class, and continue through the semester. Teaching Assistant Office Hours are (mostly) held in WG-56 (Computing Lab) or WG-67 (Student Lounge) on the ground floor of the Wood building, so be sure to look in both places if you need help. All of these locations are a few steps from each other, on the ground floor of the Wood Building in the School of Medicine. The schedule will be announced during the first week of class.

